# Generated by Django 3.2.4 on 2021-09-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='serviços',
        ),
    ]
