# Generated by Django 3.2.4 on 2021-09-15 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogclass_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogclass',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogclass',
            name='conteudo',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='blogclass',
            name='tema',
            field=models.CharField(max_length=100),
        ),
    ]
