# Generated by Django 3.2.4 on 2021-09-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviços', '0002_alter_serviços_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviços',
            name='conteúdo',
            field=models.CharField(max_length=1000),
        ),
    ]
